// <auto-generated />
using System;
using Ecommerce.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Core.Entities.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics",
                            description = "Devices and gadgets"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Books",
                            description = "Books and literature"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Clothing",
                            description = "Apparel and accessories"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Home Appliances",
                            description = "Household items and appliances"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Toys",
                            description = "Toys and games for children"
                        });
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.LocalUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LocalUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ahmed@example.com",
                            Name = "Ahmed Haggag",
                            Password = "password123",
                            Phone = "1234567890",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "tarek@example.com",
                            Name = "Tarek Sharim",
                            Password = "password456",
                            Phone = "0987654321",
                            Role = "User"
                        },
                        new
                        {
                            Id = 3,
                            Email = "sara@example.com",
                            Name = "Sara Ali",
                            Password = "password789",
                            Phone = "1122334455",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.OrderDetiles", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id", "OrderId", "ProductId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Price = 299.99m,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 4,
                            Price = 9.99m,
                            Quantity = 2m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            ProductId = 3,
                            Price = 19.99m,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 3,
                            ProductId = 2,
                            Price = 799.99m,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 3,
                            ProductId = 5,
                            Price = 49.99m,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 6,
                            OrderId = 4,
                            ProductId = 6,
                            Price = 499.99m,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 7,
                            OrderId = 4,
                            ProductId = 8,
                            Price = 14.99m,
                            Quantity = 2m
                        },
                        new
                        {
                            Id = 8,
                            OrderId = 5,
                            ProductId = 7,
                            Price = 99.99m,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 9,
                            OrderId = 5,
                            ProductId = 9,
                            Price = 9.99m,
                            Quantity = 3m
                        });
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.Orders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LocalUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocalUserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LocalUserId = 1,
                            OrderDate = new DateTime(2023, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            LocalUserId = 2,
                            OrderDate = new DateTime(2023, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Completed"
                        },
                        new
                        {
                            Id = 3,
                            LocalUserId = 1,
                            OrderDate = new DateTime(2023, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Shipped"
                        },
                        new
                        {
                            Id = 4,
                            LocalUserId = 3,
                            OrderDate = new DateTime(2023, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Pending"
                        },
                        new
                        {
                            Id = 5,
                            LocalUserId = 3,
                            OrderDate = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Completed"
                        });
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Smartphone",
                            Price = 299.99m,
                            image = "smartphone.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Laptop",
                            Price = 799.99m,
                            image = "laptop.jpg"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Name = "Novel",
                            Price = 19.99m,
                            image = "novel.jpg"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Name = "T-Shirt",
                            Price = 9.99m,
                            image = "tshirt.jpg"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Name = "Jeans",
                            Price = 49.99m,
                            image = "jeans.jpg"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            Name = "Washing Machine",
                            Price = 499.99m,
                            image = "washing_machine.jpg"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Name = "Microwave",
                            Price = 99.99m,
                            image = "microwave.jpg"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 5,
                            Name = "Teddy Bear",
                            Price = 14.99m,
                            image = "teddy_bear.jpg"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Name = "Toy Car",
                            Price = 9.99m,
                            image = "toy_car.jpg"
                        });
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.OrderDetiles", b =>
                {
                    b.HasOne("Ecommerce.Core.Entities.Orders", "Order")
                        .WithMany("OrderDetiles")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.Core.Entities.Products", "Product")
                        .WithMany("OrderDetiles")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.Orders", b =>
                {
                    b.HasOne("Ecommerce.Core.Entities.LocalUser", "LocalUser")
                        .WithMany("Orders")
                        .HasForeignKey("LocalUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalUser");
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.Products", b =>
                {
                    b.HasOne("Ecommerce.Core.Entities.Categories", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.Categories", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.LocalUser", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.Orders", b =>
                {
                    b.Navigation("OrderDetiles");
                });

            modelBuilder.Entity("Ecommerce.Core.Entities.Products", b =>
                {
                    b.Navigation("OrderDetiles");
                });
#pragma warning restore 612, 618
        }
    }
}
